#!/bin/python3

import math
import os
import random
import re
import sys

from collections import Counter
from functools import reduce
from operator import iconcat

def getSentences(text):
    return text.lower().split('.')

def getTrigrams(sentence):
    words = sentence.split()
    return [" ".join(words[i:i+3]) for i in range(len(words)-2)]


if __name__ == '__main__':
    s = input()

trigrams = Counter(reduce(iconcat, map(getTrigrams, getSentences(s)), []))
print(max(trigrams, key=trigrams.get))
